Shared.Clothing.police = {
    ['male'] = {
        ['Koppelriemen'] = {
            ['Verwijder Koppelriem'] = { ped = 'mp_m_freemode_01', components = { { 8, 16, 1 }, }, },
            ['Koppelriem 1'] = { ped = 'mp_m_freemode_01', components = { { 8, 42, 3 }, }, },
            ['Koppelriem 2'] = { ped = 'mp_m_freemode_01', components = { { 8, 24, 1 }, }, },
            ['Koppelriem 3'] = { ped = 'mp_m_freemode_01', components = { { 8, 38, 1 }, }, },
            ['Koppelriem 4'] = { ped = 'mp_m_freemode_01', components = { { 8, 58, 1 }, }, },
            ['Koppelriem 5'] = { ped = 'mp_m_freemode_01', components = { { 5, 1, 1 }, { 8, 89, 1 }, }, },
            ['Koppelriem 6'] = { ped = 'mp_m_freemode_01', components = { { 8, 67, 1 }, }, },
            ['Koppelriem 7'] = { ped = 'mp_m_freemode_01', components = { { 8, 44, 1 }, }, },
            ['Koppelriem 8'] = { ped = 'mp_m_freemode_01', components = { { 8, 52, 1 }, }, }, 
            ['Koppelriem 9'] = { ped = 'mp_m_freemode_01', components = { { 8, 48, 1 }, }, },
        },
        ['Handschoenen'] = {
            ['Geen Handschoenen kort'] = { ped = 'mp_m_freemode_01', components = { { 3, 1, 1 }, }, },
            ['Geen Handschoenen lang'] = { ped = 'mp_m_freemode_01', components = { { 3, 13, 1 }, }, },
            ['Zwarte Handschoenen kort'] = { ped = 'mp_m_freemode_01', components = { { 3, 31, 1 }, }, },
            ['Zwarte Handschoenen lang'] = { ped = 'mp_m_freemode_01', components = { { 3, 32, 1 }, }, },
            ['Dokters Handschoenen kort'] = { ped = 'mp_m_freemode_01', components = { { 3, 86, 1 }, }, },
            ['Dokters Handschoenen Lang'] = { ped = 'mp_m_freemode_01', components = { { 3, 87, 1 }, }, },
        },
        ['Kogelwerende Vesten'] = {
            ['Politie'] = { ped = 'mp_m_freemode_01', components = { { 10, 45, 1 }, }, },
            ['Recherche - Zwart'] = { ped = 'mp_m_freemode_01', components = { { 9, 22, 9 }, }, },
            ['Recherche - Blauw'] = { ped = 'mp_m_freemode_01', components = { { 9, 22, 10 }, }, },
            ['Verwijder Vest Politie'] = { ped = 'mp_m_freemode_01', components = { { 10, 1, 1 }, }, },
            ['Verwijder Vest Recherche'] = { ped = 'mp_m_freemode_01', components = { { 9, 1, 1 }, }, },
        },
        ['Rangen - Lang'] = {
            ['Aspirant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 8, 42, 3 },
                    { 7, 1, 1 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 1 },	
                },
            }, ['Surveillant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 2 },	
                },
            }, ['Agent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 3 },	
                },
            }, ['Hoofdagent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 4 },	
                },
            }, ['Brigadier'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },		
                    { 11, 144, 5 },	
                },
            }, ['Inspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 6 },	
                },
            }, ['Hoofd Inspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 7 },	
                },
            }, ['Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 8 },	
                },
            }, ['Hoofd Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 6, 26, 1 },
                    { 5, 1, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 9 },	
                },
            }, ['Eerste Hoofd Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 144, 10 },	
                },
            },
        },
        ['Rangen - Kort'] = {
            ['Aspirant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 1 },	
                },
            }, ['Surveillant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },		
                    { 11, 75, 2 },	
                },
            }, ['Agent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 3 },	
                },
            }, ['Hoofdagent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 4 },	
                },
            }, ['Brigadier'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 5 },	
                },
            }, ['Inspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 6 },	
                },
            }, ['Hoofd Inspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 7 },	
                },
            }, ['Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 8 },	
                },
            }, ['Hoofd Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 9 },	
                },
            }, ['Eerste Hoofd Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 75, 10 },	
                },
            },
        },
        ['Uniformen'] = {
            ['Mobiele Eenheid'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 8, 1 },
                    { 1, 0, 0 },
                    { 2, 0, 0 },
                },
                components = {
                    { 1, 32, 1 },
                    { 3, 32, 1 },
                    { 4, 34, 1 },
                    { 5, 0, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 }, 
                    { 8, 16, 1 }, 
                    { 9, 1, 4 },
                    { 10, 10, 1 },
                    { 11, 119, 5 },			
                },
            }, ['EOD'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 94, 2 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 36, 1 },	
                    { 4, 12, 1 },
                    { 5, 1, 1 },
                    { 6, 14, 1 },
                    { 7, 1, 1 },
                    { 8, 16, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 47, 1 },	
                },
            }, ['IBT Docent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 1, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 6, 2 },
                    { 8, 42, 4 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 52, 3 },	
                },
            }, ['Bewakings Eenheid 1'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 14, 7 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 18, 1 },	
                    { 3, 108, 10 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 3, 1 },
                    { 8, 42, 3 },
                    { 9, 8, 2 },
                    { 10, 1, 1 },	
                    { 11, 112, 4 },	
                },
            }, ['Bewakings Eenheid 2'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 14, 7 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 18, 1 },	
                    { 3, 108, 10 },	
                    { 4, 5, 7 },
                    { 5, 1, 1 },
                    { 6, 8, 7 },
                    { 7, 3, 1 },
                    { 8, 42, 3 },
                    { 9, 8, 2 },
                    { 10, 1, 1 },	
                    { 11, 112, 4 },	
                },
            }, ['Team Parate Eenheid'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 14, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 18, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 6, 1 },
                    { 8, 42, 3 },
                    { 9, 12, 3 },
                    { 10, 1, 1 },	
                },
            }, ['Politie Jas'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 0 },
                    { 10, 1, 1 },	
                    { 11, 119, 9 },	
                },
            }, ['DKDB'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 5, 1 },	
                    { 4, 29, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 11, 1 },
                    { 8, 11, 1 },
                    { 9, 1, 2 },
                    { 10, 1, 1 },	
                    { 11, 5, 1 },	
                },
            }, ['Zulu Uniform'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 74, 3 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 45, 1 },	
                    { 4, 112, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 16, 1 },	
                },
            }, ['Ondersteunings Groep'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 14, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 73, 1 },	
                    { 3, 106, 10 },	
                    { 4, 5, 7 },
                    { 5, 1, 1 },
                    { 6, 16, 4 },
                    { 7, 3, 1 },
                    { 8, 16, 1 },
                    { 9, 8, 1 },
                    { 10, 16, 1 },	
                    { 11, 216, 2 },
                    
                },
            }, ['Politie - Training Uniform'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 1, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 6, 2 },
                    { 8, 42, 4 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 148, 2 },		
                },
            }, ['Politie - Schiet Training Uniform'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 1, 1 },	
                    { 1, 16, 10 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 1, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 6, 2 },
                    { 8, 42, 4 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 148, 2 },		
                },
            }, ['Unmarked Lang'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 39, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 112, 2 },	
                },
            }, ['Wegmisbruikers'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 5, 7 },
                    { 5, 1, 1 },
                    { 6, 58, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 19, 3 },
                    { 10, 10, 1 },	
                    { 11, 148, 1 },	
                },
            }, ['Unmarked Kort 1  '] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 27, 7 },
                    { 10, 1, 1 },	
                    { 11, 32, 2 },	
                },
            }, ['Unmarked Kort 2  '] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 16, 4 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 32, 2 },	
                },
            },
        },
        ['Recherche'] = {
            ['Forensische Opsporing 1'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 57, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 6, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 19, 1 },	
                },
            }, ['Forensische Opsporing 2'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 87, 1 },	
                    { 4, 41, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 62, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 68, 1 },	
                },
            }, ['Recherche Jas'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 5, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 8, 7 },
                    { 7, 1, 1 },
                    { 8, 11, 1 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 37, 1 },	
                },
            }, ['Recherche T-Shirt'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 31, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 8, 7 },
                    { 7, 6, 1 },
                    { 8, 42, 3 },
                    { 9, 21, 1 },
                    { 10, 1, 1 },	
                    { 11, 243, 1 },	
                },
            }, ['(K) Rechercheur Uniform 1'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 13, 1 },	
                    { 4, 29, 1 },
                    { 5, 26, 1 },
                    { 6, 11, 1 },
                    { 7, 13, 1 },
                    { 8, 94, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 102, 1 },	
                },
            }, ['Rijksrecherche Uniform'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 38, 1 },	
                    { 4, 29, 1 },
                    { 5, 26, 1 },
                    { 6, 11, 1 },
                    { 7, 1, 1 },
                    { 8, 94, 1 },
                    { 9, 9, 2 },
                    { 10, 1, 1 },	
                    { 11, 14, 1 },	
                },
            }, ['(K) Rechercheur Uniform 2'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 13, 1 },	
                    { 4, 29, 1 },
                    { 5, 26, 1 },
                    { 6, 11, 1 },
                    { 7, 22, 8 },
                    { 8, 94, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 50, 1 },	
                },
            }, ['(K) Holster 1'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 57, 1 },
                },
            }, ['(K) Holster 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 8, 17, 1 },
                },
            }, ['Recherche In Burger'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 5, 1 },	
                    { 4, 5, 3 },
                    { 5, 1, 1 },
                    { 6, 58, 1 },
                    { 7, 1, 1 },
                    { 8, 16, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 87, 5 },	
                },
            },
        },
        ['Training'] = {
            ['Oog- & Gehoorbeschermers'] = {
                category = 'TRAINING',
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 1, 1 },	
                    { 1, 16, 10 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {},
            }, ['Training Koppel'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 8, 42, 4 },
                },
            }, ['Training Holster'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 7, 6, 2 },
                },
            },
        },
        ['Overig'] = {
            ['Politie Muts'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 3, 6 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                },
            }, ['Politie Pet'] = {
                category = 'Overig',
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 11, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                }, 
            }, 
            ['Oortje 1'] = { ped = 'mp_m_freemode_01', components = { { 1, 32, 1 }, }, }, 
            ['Oortje 2'] = { ped = 'mp_m_freemode_01', components = { { 1, 142, 1 }, }, },
            ['Oortje 3'] = { ped = 'mp_m_freemode_01', components = { { 1, 145, 1 }, }, },
            ['Politie Badge'] = { ped = 'mp_m_freemode_01', components = { { 9, 21, 1 }, }, },
            ['Officier van Justitie Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 11, 2 }, }, },
            ['Politie Geel Reflectie Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 11, 3 }, }, }, 
            ['Openbaar Ministerie Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 29, 3 }, }, },
            ['OPCO Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 29, 4 }, }, },
            ['Waarnemer Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 29, 5 }, }, },
            ['Oefenleiding Hesje'] = { ped = 'mp_m_freemode_01', components = { { 9, 29, 7 }, }, },
        },
        ['Holsters'] = {
            ['Tazer Holster 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 55, 1 }, 
                    { 7, 1, 1 },
                },
            }, ['Tazer Holster 2 (Alternatief)'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 10, 21, 1 },	
                },
            }, ['Been Holster + EHBO Tas'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 44, 1 },
                },
            }, ['Been Holster + Tazer 2 + EHBO Tas'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 55, 1 }, 
                    { 7, 44, 1 },
                },
            }, ['Been Holster 2 + Tazer 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 55, 1 }, 
                    { 7, 7, 1 },
                },
            }, ['Geen Vuurwapen + Tazer Holster'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 1, 1 },
                    { 10, 1, 1 },	
                },
            }, ['Been Holster 1'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 3, 1 },
                },
            }, ['Koppel Holster 1'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 6, 1 },
                },
            }, ['Koppel Holster + Tazer 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 55, 1 }, 
                    { 7, 6, 1 },
                },
            }, ['Been Holster 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 7, 1 },
                },
            }, ['Been Holster 1 + Tazer 1'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 1, 1 }, 
                    { 7, 4, 1 },
                },
            }, ['Been Holster 1 + Tazer 2'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 5, 55, 1 }, 
                    { 7, 3, 1 },
                },
            },
        },
        ['Motor Uniformen'] = {
            ['Unmarked Uniform 1'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 53, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 43, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 13, 7 },
                    { 7, 1, 1 },
                    { 8, 75, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 249, 1 },	
                },
            }, ['Unmarked Uniform 2'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 53, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 43, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 13, 7 },
                    { 7, 1, 1 },
                    { 8, 78, 2 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 245, 6 },	
                },
            }, ['Unmarked Uniform 3'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 2 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 43, 1 },	
                    { 4, 5, 6 },
                    { 5, 1, 1 },
                    { 6, 13, 7 },
                    { 7, 1, 1 },
                    { 8, 78, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 245, 8 },	
                },
            }, ['Aspirant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 1 },	
                },
            }, ['Surveillant'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 2 },	
                },
            }, ['Agent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 3 },	
                },
            }, ['Hoofdagent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 4 },	
                },
            }, ['Brigadier'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 5 },	
                },
            }, ['Inspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 6 },	
                },
            }, ['Hoofdinspecteur'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 7 },	
                },
            }, ['Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 8 },	
                },
            }, ['Hoofdcommissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 9 },	
                },
            }, ['Eerste Hoofd Commissaris'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 32, 1 },	
                    { 4, 68, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 42, 3 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 222, 10 },	
                },
            },
        },
        ['Steekvesten'] = {
            ['TEV'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 9 },
                    { 10, 1, 1 },
                },
            }, ['Wijkagent'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 4 },
                    { 10, 1, 1 },
                },
            }, ['Unmarked 2'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 7 },
                    { 10, 1, 1 }
                },
            }, ['Unmarked'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 3 },
                    { 10, 1, 1 }
                },
            }, ['Noodhulp'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },		
                    { 9, 27, 1 },
                    { 10, 1, 1 }
                },
            }, ['Geel reflectie'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 2 },
                    { 10, 1, 1 }
                },
            }, ['Verkeerspolitie'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 6 },	
                    { 10, 1, 1 }
                },
            }, ['Bike team'] = {
                ped = 'mp_m_freemode_01',
                props = {
                    { 0, 34, 2 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 1 },
                    { 10, 1, 1 }
                },
            }, ['Hondengeleider'] = {
                ped = 'mp_m_freemode_01',
                components = {
                    { 1, 32, 1 },	
                    { 9, 27, 5 },
                    { 10, 1, 1 }
                },
            },
        }
    },
    ['female'] = {
        ['Handschoenen'] = {
            ['Dokters Handschoenen Kort'] = { ped = 'mp_f_freemode_01', components = { { 3, 110, 1 }, }, },
            ['Dokters Handschoenen Lang'] = { ped = 'mp_f_freemode_01', components = { { 3, 102, 1 }, }, },
            ['Zwarte Handschoenen Kort'] = { ped = 'mp_f_freemode_01', components = { { 3, 47, 1 }, }, },
            ['Zwarte Handschoenen Lang'] = { ped = 'mp_f_freemode_01', components = { { 3, 50, 1 }, }, },
            ['Verwijder Handschoenen Kort'] = { ped = 'mp_f_freemode_01', components = { { 3, 15, 1 }, }, },
            ['Verwijder Handschoenen Lang'] = { ped = 'mp_f_freemode_01', components = { { 3, 4, 1 }, }, },
        },
        ['Koppelriemen'] = {
            ['Koppelriem 1'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 8, 3, 1 },
                    { 10, 1, 1 },
                },
            },
            ['Koppelriem 2'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 8, 15, 1 },
                    { 10, 2, 1 },
                },
            },
        },
        ['Kogelwerende Vest'] = {
            ['Politie '] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 7 }, }, },
            ['Kogelwerend Vest'] = { ped = 'mp_f_freemode_01', components = { { 9, 1, 1 },}, },
        },
        ['Holsters'] = {
            ['Taser Holster'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 55, 1 },	
                },
            },
            ['Been Holster 3 + EHBO Tas'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 7, 10, 1 },	
                },
            },
            ['Been Holster 1'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 7, 3, 1 },	
                },
            },
            ['Been Holster 1 + Tazer'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 7, 4, 1 },	
                },
            },
            ['Been Holster 2'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 7, 7, 1 },	
                },
            },
            ['Koppel Holster 1'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },
                    { 7, 6, 1 },	
                },
            },
            ['Verwijder Holster'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 5, 1, 1 },	
                    { 7, 1, 1 },	
                },
            },
        },
        ['Motor Agent Uniformen'] = {
            ['Aspirant'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 1 },
                },
            }, ['Surveillant'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 2 },
                },
            }, ['Agent'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 3 },
                },
            }, ['Hoofdagent'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 4 },
                },
            },['Brigadier'] = { 
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 5 },
                },
            }, ['Inspecteur'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 6 },
                },
            }, ['Hoofdinspecteur'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 7 },
                },
            }, ['Commissaris'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 8 },
                },
            }, ['Hoofdcommissaris'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 9 },
                },
            }, ['Eerste Hoofdcommissaris'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 18, 1 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 32, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 1, 1 },
                    { 10, 2, 1 },
                    { 11, 36, 10 },
                },
            },
        },
        ['Uniformen'] = {
            ['Opvallend Kort'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 34, 1 },	
                    { 4, 101, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 7, 3 },
                    { 10, 2, 1 },	
                    { 11, 86, 1 },
                },
            }, ['Opvallend Lang'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 101, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 15, 1 },
                    { 9, 32, 1 },
                    { 10, 2, 1 },	
                    { 11, 120, 1 },
                },
            }, ['Mobiele Eenheid'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 37, 1 },	
                    { 4, 49, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 4, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 120, 3 },
                },
            }, ['Unmarked Kort'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 15, 1 },	
                    { 4, 78, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 7, 1 },
                    { 8, 16, 1 },
                    { 9, 1, 1 },
                    { 10, 4, 1 },	
                    { 11, 74, 2 },
                },
            }, ['Unmarked Lang'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 2, 1 },	
                    { 4, 78, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 7, 1 },
                    { 8, 16, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 64, 1 },
                },
            },
        },
        ['Steekvesten'] = {
            ['Verwijder Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 1, 1 }, }, },
            ['Noodhulp Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 1 }, }, },
            ['Geel Reflectie Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 2 }, }, },
            ['Team Verkeer Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 3 }, }, },
            ['Wijkagent Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 4 }, }, }, 
            ['TEV Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 5 }, }, }, 
            ['Hondengeleider Steekvest'] = { ped = 'mp_f_freemode_01', components = { { 9, 32, 6 }, }, },
        },
        ['Hesjes'] = {
            ['Verwijder Hesje'] = { ped = 'mp_f_freemode_01', components = { { 9, 1, 1 }, }, },
            ['OM Hesje'] = { ped = 'mp_f_freemode_01', components = { { 9, 20, 5 }, }, },
            ['OvJ Hesje'] = { ped = 'mp_f_freemode_01', components = { { 9, 20, 9 }, }, },
            ['Geel Reflectie Vest'] = { ped = 'mp_f_freemode_01', components = { { 9, 20, 1 }, }, },
            ['OVD-P'] = { ped = 'mp_f_freemode_01', components = { { 9, 20, 7 }, }, },
        },
        ['Recherche'] = {
            ['Forensische opsporing'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 1, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 32, 1 },	
                    { 3, 102, 1 },	
                    { 4, 41, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 43, 1 },
                    { 9, 1, 1 },
                    { 10, 1, 1 },	
                    { 11, 62, 1 },
                },
            },
            ['(K) Holster 1'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 8, 54, 1 },
                },
            }, ['(K) Holster 2'] = {
                ped = 'mp_f_freemode_01',
                components = {
                    { 8, 10, 1 },
                },
            }, ['(K) Rechercheur Uniform 1'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 4, 1 },	
                    { 4, 7, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 21, 1 },
                    { 8, 54, 1 },
                    { 9, 1, 1 },
                    { 10, 4, 1 },	
                    { 11, 141, 1 },
                },
            }, ['(K) Rechercheur Uniform 2'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 4, 1 },	
                    { 4, 7, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 23, 1 },
                    { 8, 54, 1 },
                    { 9, 1, 1 },
                    { 10, 4, 1 },	
                    { 11, 141, 1 },
                },
            }, ['Recherche Jas'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 8, 1 },	
                    { 4, 78, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 7, 1 },
                    { 8, 60, 1 },
                    { 9, 1, 1 },
                    { 10, 4, 1 },	
                    { 11, 180, 2 },
                },
            }, ['Recherche T-Shirt'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 15, 1 },	
                    { 4, 78, 1 },
                    { 5, 1, 1 },
                    { 6, 26, 1 },
                    { 7, 1, 1 },
                    { 8, 10, 1 },
                    { 9, 24, 1 },
                    { 10, 1, 1 },	
                    { 11, 251, 1 },
                },
            }, ['Rijksrecherche Uniform'] = {
                ped = 'mp_f_freemode_01',
                props = {
                    { 0, 0, 0 },	
                    { 2, 0, 0 },	
                    { 3, 0, 0 },	
                },
                components = {
                    { 1, 1, 1 },	
                    { 3, 4, 1 },	
                    { 4, 7, 1 },
                    { 5, 1, 1 },
                    { 6, 11, 1 },
                    { 7, 23, 1 },
                    { 8, 54, 1 },
                    { 9, 2, 2 },
                    { 10, 4, 1 },	
                    { 11, 141, 1 },
                },
            },
        }
    }
}